fortunes:
  list:
    - "You will have a great day!"
    - "Success is just around the corner."
    - "Hard work pays off!"
    - "Careful, it can be a mannequin!"
    - "Don't believe everything you read."
    - "Objects in the mirror are closer than they appear."
    - "Give me some sunshine, give me some rain."
    - "Never go outside your house unalert."
    - "Where there is a will, there is bad luck"
    - "Four out of five people are scared to fight."
    - "There is a ray of hope at the end of every dark tunnel."